export interface Datos{
cedula?: number|string,
tipoCedula1?: string,
tipoCedula2?: string,
primerNombre?: string,
segundoNombre?: string,
primerApellido?: string,
segundoApellido?: string,
telefono?:number|string,
direccion?: string,
correo?: string,
tipoUsuario1?: string,
tipoUsuario2?: string,
contrasena?: string,
confirmarContrasena?: string,
facultad?:string,
semestre?:string|number,
}